#!/bin/bash

. $HOME/.bin/colr

bspc config border_width       3
bspc config window_gap         20
bspc config top_padding	30

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color "#$cyn"
bspc config active_border_color "#$bblk"
bspc config normal_border_color "#$bblk"
bspc config normal_locked_border_color "#$fg"
bspc config focused_sticky_border_color "#$mag"
bspc config active_sticky_border_color '#cc99cc'
bspc config normal_sticky_border_color '#d3d0c8'
bspc config focused_private_border_color '#cc99cc'
bspc config active_private_border_color '#cc99cc'
bspc config normal_private_border_color '#cc99cc'
bspc config urgent_border_color '#f2777a'
bspc config focus_by_distance false

bspc monitor -d I II III IV V
bspc rule -a bar state=locked follow=on
