#!/bin/bash

. $HOME/.bin/colr

if [[ $(hostname) = "globbox" ]]; then
	bspc config border_width       2
	bspc config window_gap         10
	bspc config top_padding	54
	bspc config left_padding 105
	bspc config right_padding 105
	bspc config bottom_padding 54
else
	bspc config border_width	4
	bspc config window_gap 20
	bspc config top_padding 50
fi

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focused_border_color "#$fg"
bspc config active_border_color "#$bblk"
bspc config normal_border_color "#$bblk"
bspc config normal_locked_border_color "#$fg"
bspc config focused_sticky_border_color "#$red"
bspc config active_sticky_border_color "#$cyn"
bspc config normal_sticky_border_color "#$red"
bspc config focused_private_border_color '#cc99cc'
bspc config active_private_border_color '#cc99cc'
bspc config normal_private_border_color '#cc99cc'
bspc config urgent_border_color '#f2777a'
bspc config focus_by_distance false
bspc config focus_follows_mouse true
bspc monitor -d I II III IV V
bspc rule -a bar state=locked follow=on

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi
