#!/bin/bash
super + alt + Escape
	bspc quit

super + {_,shift} + c
	bspc desktop -C {backward, forward}

super + {t, f, p}
	bspc window -t {floating, fullscreen, sticky}

super + q
	killw $(pfw)	

super + {h, j, k, l}
	wmv {-25 0, 0 25, 0 -25, 25 0} $(pfw)

super + alt + {h, j, k, l}
	wrs {-25 0, 0 25, 0 -25, 25 0} $(pfw)

super + x 
	cornerw md $(pfw)

super + m
	bspc window -s biggest

super + {_,shift} + Tab
	bspc window -f {prev, next}

super + Return
	urxvt

~button1
	bspc pointer -g focus

super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

super + !button{1-3}
	bspc pointer -t %i %i

super + @button{1-3}
	bspc pointer -u

super + space
	menu

super + r
	bspc desktop -R 90

alt + {h, j, k, l}
	bspc window -f {left, down, up, right}

super + {1-5}
	bspc desktop -f {I, II, III, IV, V}

super + shift + {1-5}
	bspc window -d {I, II, III, IV, V}

alt + {minus, equal}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap ` {+, -} 10 ))

super + Escape
	pkill sxhkd && sxhkd && xrdb -load ~/.Xresources

super + {Left, Down, Right, Up}
	bspc window -e {left, down, right, up} .1

super + {b, e}
	bspc desktop -{B,E}
