#!/bin/sh
super + alt + Escape
	pkill xwait

super + q
	killw $(pfw)	

super + {h, j, k, l}
	wmv {-20 0, 0 20, 0 -20, 20 0} $(pfw)

super + alt + {h, j, k, l}
	wrs {-20 0, 0 20, 0 -20, 20 0} $(pfw)

super + c
	cornerw md $(pfw)

super + Tab
	focuswrap next

super + shift + Tab
	focuswrap prev

super + Escape
	pkill -USR1 -x sxhkd

super + Return
	urxvt

super + space
	menu
