#!/bin/bash

. $HOME/.bin/colr
pkill bar
bspc config pointer_motion_interval 1
bspc config click_to_focus true
bspc config border_width 3
bspc config window_gap 20
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config split_ratio         0.5
bspc config focused_border_color "#$blu"
bspc config active_border_color "#$bg"
bspc config normal_border_color "#$bg"
bspc config presel_feedback_color "#$blu"
bspc config ignore_ewmh_focus true
bspc monitor DVI-D-0 -d 0 1 2 3 4
bspc monitor DVI-I-1 -d 0 1 2 3 4
bspc monitor DP-0 -d 0 1 2 3 4
bspc rule -a bar state=locked follow=on
bspc rule -a Steam desktop='^4' state=floating follow=false
bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a Deluge desktop='^5' follow=false
xrdb ~/.Xresources
hsetroot -tile "$HOME/.wp/dfs.png"

xrandr --output DP-0 --left-of DVI-I-1 --rotate normal --mode 1920x1080
xrandr --output DVI-D-0 --right-of DVI-I-1 --rotate left --mode 1920x1080

bspc config top_padding 0
#bars &
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi
