#!/bin/bash

. $HOME/.bin/colr
bspc config pointer_motion_interval 1
bspc config click_to_focus true
bspc config border_width 2
bspc config window_gap 5
bspc config top_padding	15
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focused_border_color "#$red"
bspc config active_border_color "#$bblk"
bspc config normal_border_color "#$bblk"
bspc config presel_feedback_color "#$red"
bspc config ignore_ewmh_focus true
bspc monitor DVI-I-1 -d I II III IV V VI VII VIII IX X
bspc rule -a bar state=locked follow=on
bspc rule -a Steam desktop='^4' state=floating follow=false
bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a Deluge desktop='^9' follow=false
xrdb ~/.Xresources
hsetroot -tile "/home/errl/Pictures/escheresque_ste.png"
pkill bar
    runbar &
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi
