#!/bin/bash

. $HOME/.bin/colr
SEP="    "
SEP2="  "
Clock() {
	echo "%{A:pkill xinit:}%{+u}%{U#$fg}$SEP$(date +%c)$SEP%{U-}%{-u}%{A}"
}

WS() {
	switcher=""
	for desktop in $(bspc query -D); do
		if [[ $desktop = $(bspc query -D -d) ]]; then
			switcher="$switcher%{F#$cyn}%{+u}%{U#$cyn}$SEP2  $SEP2%{U-}%{-u}%{F-}"
		elif [[ $(bspc query -N -d $desktop | wc -l) -gt 0 ]]; then
			switcher="$switcher%{A:bspc desktop -f $desktop:}$SEP2  $SEP2%{A}"
		else
			switcher="$switcher%{A:bspc desktop -f $desktop:}$SEP2  $SEP2%{A}"
		fi
	done
	echo "$switcher"
}

Todo() {
	echo "%{A:todo:}%{F#$fg} %{F-}$(cat .todo | wc -l)%{A}"
}

Track() {
	prefix=""
	if [[ $(mpc | grep playing) != "" ]]; then
		prefix="%{+u}%{U#$fg}"
	fi
		echo "%{A:mpc toggle:}$prefix$SEP2 $(mpc | grep -)$SEP2%{U-}%{-u}%{A}"
}

Weather() {
	echo "$(weather-report 47906 | grep Temp | tail -c 15 | head -c 5)"
}

Name() {
	echo "$SEP$(whoami)@$(hostname)$SEP"
}

Music() {
	echo "$(mpc | grep volume | head -c 12 | tail -c 5)"
}

echo "$(Track)%{c}$(WS)%{r}$SEP$(Music)$(Weather)$(Todo)$SEP2$(Clock)"
