#!/bin/bash

. $HOME/.bin/colr
SEP="    "
SEP2="  "
Clock() {
	echo "%{A3:bspc quit:}$SEP$(date +%c)$SEP%{A}"
}

WS() {
	switcher=""
	for desktop in $(bspc query -D); do
		if [[ $desktop = $(bspc query -D -d) ]]; then
			switcher="$switcher%{F#$cyn}%{+u}%{U#$cyn}$SEP2  $SEP2%{U-}%{-u}%{F-}"
		elif [[ $(bspc query -N -d $desktop | wc -l) -gt 0 ]]; then
			switcher="$switcher%{A:bspc desktop -f $desktop:}$SEP2  $SEP2%{A}"
		else
			switcher="$switcher%{A:bspc desktop -f $desktop:}$SEP2  $SEP2%{A}"
		fi
	done
	echo "$switcher"
}
Weather() {
	echo "$(weather-report 47906 | grep Temp | tail -c 16 | head -c 8)"
}

echo "%{c}$(WS)%{r}$SEP$(Music)$(Todo)$SEP2$(Clock)"
