#!/bin/sh

. $HOME/.bin/colr
line=""
SEP="   "
while :; do
	while read -r line ; do
		case $line in
			%C*)
			clock="$(echo $line | cut -c 3-)"
			;;
			%W*)
			wm="$(echo $line | cut -c 3-)"
		esac
	done
	line="%{l}$SEP${wm}%{r}%{F#$bg}%{B#$red}$SEP${clock}$SEP%{B-}%{F-}"
	if [[ "$line" != "$last" ]]; then
		last="$line"
		echo "$line"
	fi
done
