#!/bin/sh

. $HOME/.bin/colr
line=""
SEP="   "
while :; do
	while read -r line ; do
		case $line in
			%C*)
			clock="$(echo $line | cut -c 3-)"
			;;
			%W*)
			wm="$(echo $line | cut -c 3-)"
			;;
			%N*)
			inet="$(echo $line | cut -c 3-)"
		esac
	done
	line="%{l}$SEP${wm}$SEP  %{r}${vpn}   ${clock}   "
	if [[ "$line" != "$last" ]]; then
		last="$line"
		echo "$line"
	fi
done
