#!/usr/bin/python

import subprocess

output = subprocess.getoutput('mpc').split('\n')
status = output[1].split(' ')[0][:-1][1:]
volume = output[2].split(':')[1][:-9]

if status == 'playing':
	color = '%{F#799c6a}'
else:
	color = '%{F#996140}'

print(color + '%{A:mpc toggle:}' + status + '%{A}%{F-}')

