#!/bin/sh

. $HOME/.bin/colr

[ -e "/tmp/barfifo" ] && rm "/tmp/barfifo"
mkfifo "/tmp/barfifo"
#echo "%C$(date +"%a, %d %b %Y %I:%M:%S %p")" > "/tmp/barfifo" &
clock &

if [[ $(hostname) = "globbox" ]]; then
	settings="-f lemon:size=8 -g 1520x25+200+10 "
else
	settings="-f RobotoMono:size=9 -g 2880x40+0+0 "
fi

bar < /tmp/barfifo | lemonbar ${settings} -F"#$fg" -B"#$bg" -p | sh
