#!/bin/sh

. $HOME/.bin/colr

[ -e "/tmp/barfifo" ] && rm "/tmp/barfifo"
mkfifo "/tmp/barfifo"
clock &
loop &
np &
if [[ $(hostname) = "globbox" ]]; then
	settings="-o -1 -f lemon:size=8 -g 1920x25+0+0 -o 1 -f FontAwesome:size=10"
else
	settings="-f RobotoMono:size=11 -g 2880x50+0+0 "
fi

bar < /tmp/barfifo | lemonbar ${settings} -F"#$fg" -B"#00$bg" -p | sh
