#!/bin/sh

. $HOME/.bin/colr

[ -e "/tmp/barfifo" ] && rm "/tmp/barfifo"
mkfifo "/tmp/barfifo"
#echo "%C$(date +"%a, %d %b %Y %I:%M:%S %p")" > "/tmp/barfifo" &
clock &
bar < /tmp/barfifo | lemonbar -f lemon:size=8 -F"#$fg" -B"#$bg" -g 1520x25+200+10 -p | sh
