#!/bin/sh

. $HOME/.bin/colr
if [[ $(hostname) = "globtop" ]]; then
	font="RobotoMono 12"
else
	font="Lemon 8"
fi

rofi -show run -padding 10 -bg "#$bg" -fg "#$fg" -hlbg "#$red" -hlfg "#$bg" -location 0 -font "$font" -bc "#$red" -bw 2
