#!/bin/sh

. $HOME/.bin/colr
if [[ $(hostname) = "globtop" ]]; then
	font="RobotoMono 12"
else
	font="Lemon 8"
fi

rofi -show run -padding 10 -color-window "#$bg, #$red, #$red" -color-normal "#$bg, #$fg, #$bg, #$red, #$bg" -color-active "#$bg, #$red, #$red, #$bg" -location 0 -font "$font" -bc "#$red" -bw 2
