#!/usr/bin/python

import subprocess, time, datetime
workspaces = subprocess.getoutput('bspc query -D').split('\n')
current = subprocess.getoutput('bspc query -D -d')
line = ""
for workspace in workspaces:
	if workspace == current:
		line += '%{B#1b1b1a}%{F#996140}  ' + workspace + '  %{F-}%{B-}'
	else:
		line += '  ' + workspace + '  '
	if workspace != workspaces[-1]:
		line += '|'
print(line)
