#!/usr/bin/python

import subprocess, time, datetime
workspaces = subprocess.getoutput('bspc query -D').split('\n')
current = subprocess.getoutput('bspc query -D -d')
line = ""
for workspace in workspaces:
	if workspace == current:
		line += '%{F#1b1b1a}%{B#966140} ' + workspace + '  %{B-}%{F-}'
	else:
		line += '%{A:bspc desktop -f ' + workspace + ':} '+ workspace + '  %{A}'
	line += ' | '
print(line)
