#!/usr/bin/python
import sys
last = ""
for line in sys.stdin:
	if line == last or line == "":
		sys.exit()
	else:
		last = line
		line = line.split(':')
		out = ""
		for i in range(1, 8):
			workspace = line[i][1:]
			out += '%{A:bspc desktop -f ' + workspace + ':}'
			if line[i].startswith('O') or line[i].startswith('F'): #Focused
				out += '%{F#996140}'
			elif line[i].startswith('o') or line[i].startswith('f'):
				out += '%{F#b0b0a2}'	
			else:
				out += '%{F#7b6064}'
			out += workspace + '%{A}%{F-}  '
	print('%W' + out)
